### ISSUE TITLE
community: add link to https://www.youtube.com/@cuelang/videos

### ISSUE THREAD

**Issue by myitcv** [cue-lang/docs-and-content#116]

**Comment by jpluscplusm** [comment]
https://cuelang.org/cl/1191482, and the felt-like-a-good-idea-to-me followup of https://cuelang.org/cl/1191485.

**Comment by jpluscplusm** [comment]
Closed via https://github.com/cue-lang/cuelang.org/commit/5ff99cb7a1a0cf90597feb39b244fe10c090571e
