### ISSUE TITLE
concept guide: explanation of "commented cue" howtos

### ISSUE THREAD

**Issue by myitcv** [cue-lang/docs-and-content#12]
Per @jpluscplusm (with light edits from the original to update given the current state of things)

In https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1167754 we started using a 95% example-driven approach for a certain class of Howto Guides - the constraint-based Guides. I'm calling this approach "CUE By Example", but I hold that term very lightly. (now renamed to `commented cue`)

Whilst we'll place some contextual comments in both the CUE and YAML input files, IMHO there's a non-trivial subset of readers who won't be able to take the examples and translate them into their own context. Again IMHO, they'll take the example CUE, paste it into a file verbatim (including our comments, sitting there unread), and either their existing CUE will break or this *new* CUE file won't achieve what they need.

I feel we can help (some of!) this set of users by writing a `commented cue` concept guide that's briefly linked to at the top of each such piece of content.

It would explain that the CUE in the Guide they're reading isn't something they should adopt verbatim. It could demonstrate (so is it actually a tutorial?) the process of translating an arbitrary `commented cue` into a different context.

**Comment by jpluscplusm** [comment]
Achieved by https://alpha.cuelang.org/docs/howto/#commented-cue-guides
