### ISSUE TITLE
all: reflect change in language towards "workflow commands"

### ISSUE THREAD

**Issue by myitcv** [cue-lang/docs-and-content#142]
Ahead of any work happening on https://github.com/cue-lang/cue/issues/1325, we need to better distinguish a user-defined command as part of a `cue cmd` workflow, from the various `cue` commands (e.g. `export`). As discussed and implemented in https://review.gerrithub.io/c/cue-lang/cue/+/1187654, that shift of language settled on "workflow commands" being those user-defined commands that are run via `cue cmd`. 

We should ensure cuelang.org docs reflect that change.

**Comment by jpluscplusm** [comment]
@myitcv I can't find anywhere that needs updating, except the unpublished, draft, k8s tutorial. It feels like busy work to update it, given that it's invisible and will need more substantial updates as&when&if we publish it on the site. I will PR an update to that doc in CUE-by-example.

- https://cuelang.org/docs/howto/use-your-first-cue-workflow-command/ is already up to date
- https://cuelang.org/docs/reference/cli/cue-commands/ and other in that hierarchy have picked up your updates from `cue-lang/cue`.

Did you have any pages in mind?

**Comment by jpluscplusm** [comment]
Believed closed by https://github.com/cue-labs/cue-by-example/commit/99be91bb68531f68de97a39ac129fea6082addd0. /cc @myitcv
