### ISSUE TITLE
concept: Modules, Packages, and Instances docs should be clarified to not imply special pkg directory

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/docs-and-content#152]
_Originally opened by @smorel-plenty in https://github.com/cuelang/cue/issues/753_

In the section on [import paths](https://cuelang.org/docs/concepts/packages/#import-path) there's a mention of `module: example.com/pkg`. I'm assuming the `pkg` here is not referring to the `pkg` cue-managed external dependencies directory but could instead be something like `module example.com/mypackage` for better clarity when reading the docs?

**Comment by myitcv** [comment]
@jpluscplusm please can you handle this?

**Comment by jpluscplusm** [comment]
Closed via https://github.com/cue-lang/cuelang.org/commit/b3d612dc3d505491a5e13419620c9d74cd48dd2a
