### ISSUE TITLE
cuelang.org playground "About" page is 404

### ISSUE THREAD

**Issue by infogulch** [cue-lang/docs-and-content#158]
The playground ( https://cuelang.org/play/ ) links to an "About CUE Playground" page ( https://cuelang.org/about-play ) which 404's.

**Comment by jpluscplusm** [comment]
I can't see any sign that this path (`/about-play`) has ever served any content, and I can't find any proposed/orphaned content in the site that could be immediately promoted. I've removed the link from the nav in https://cuelang.org/cl/1196175, and have opened #159 to track the creation (and linking) of a new About page.

**Comment by jpluscplusm** [comment]
Closed via https://github.com/cue-lang/cuelang.org/commit/021205c8ade6b35320568dae7d9e23625eb7b074
