### ISSUE TITLE
docs/howto: embed data in CUE

### ISSUE THREAD

**Issue by myitcv** [cue-lang/docs-and-content#166]
A howto guide demonstrating the single-file (`file=`) and multi-file (`glob=`) forms of the proposed `@embed()` tag.

**Comment by jpluscplusm** [comment]
https://cuelang.org/cl/1197157

**Comment by myitcv** [comment]
This was implemented and released: https://cuelang.org/docs/howto/embed-files-in-cue-evaluation/
