### ISSUE TITLE
docs/howto: use the builtin function "matchN"

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/docs-and-content#176]
https://cuelang.org/cl/1198922 introduced the new builtin `matchN()`, which will allow (at least!) JSONSchema constraints such `oneOf`, `anyOf`, and `atLeast` to be expressed idiomatically.

Let's write a how-to guide that demonstrates `matchN()` using a tip version of the `cue` command. https://cuelang.org/cl/1198922/6/cue/testdata/builtins/matchn.txtar contains several examples that we can either steal or adapt.

**Comment by mvdan** [comment]
@jpluscplusm wasn't this issue meant to be marked as fixed?

**Comment by jpluscplusm** [comment]
Closed via https://github.com/cue-lang/cuelang.org/commit/521ab46f0b896730e704ef05b47d4c45b03b2c30
