### ISSUE TITLE
FAQ regarding symlink support in CUE

### ISSUE THREAD

**Issue by myitcv** [cue-lang/docs-and-content#187]
In https://github.com/cue-lang/cue/issues/3300#issuecomment-2429401231 @rogpeppe has summarised the state of symlink support in CUE. That high-level summary, whilst accurate, arguably leaves a number of "gaps" for someone less familiar with the space, such that it's useful to have a set of FAQs that fill in the detail to specific questions. 

This issue captures the creation of such an FAQ.

**Comment by jpluscplusm** [comment]
I don't know why this issue wasn't closed automatically by https://github.com/cue-lang/cuelang.org/commit/27637077a4188e832b60f954279ce4517d67a0cd being added to `master`.
