### ISSUE TITLE
concept guide: Modules, Packages, and Instances

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/docs-and-content#20]
https://cuelang.org/docs/concepts/packages/ doesn't have a direct equivalent on alpha.

It might be absorbed into the Language Guide (possibly at https://alpha.cuelang.org/docs/language-guide/file-organization/modules/) but I'm not sure about this.

Alternatively, we could clone the existing page as a new Concept Guide on alpha.

**Comment by myitcv** [comment]
> Alternatively, we could clone the existing page as a new Concept Guide on alpha.

Good decision for now.

**Comment by jpluscplusm** [comment]
Closed via https://github.com/cue-lang/cuelang.org/commit/45850fdd6c4b7b84ce2fdd3c122f898ac0048c46. (Failed CI status is a flaky provider; issue was resolved by the time the next commit deployed alpha)
