### ISSUE TITLE
tutorial: the current site's tutorial index links to the Kubernetes tutorial

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/docs-and-content#21]
https://cuelang.org/docs/tutorials/ links to the in-repo Kubernetes tutorial (i.e. /not/ on cue-by-example) with some very visible words catching the Kube Google juice. Alpha's equivalent page does not.

Whilst https://alpha.cuelang.org/docs/introduction/welcome/ does link there, it's /way/ down the page, in passing.

**Q: how do we want the Kubernetes tutorial to be exposed on alpha?**

**Comment by myitcv** [comment]
> Q: how do we want the Kubernetes tutorial to be exposed on alpha?

With a link to the new cue-by-example tutorial, which is also updated. We should also update any links from `cue-lang/cue` too.

cc @mvdan

**Comment by jpluscplusm** [comment]
> With a link to the new cue-by-example tutorial

Just to be clear: we want a hard-coded link included on https://alpha.cuelang.org/docs/tutorial/about-these-tutorials/, pointing to the tutorial on cue-by-example?

I can't see any other way to do it *nicely*, ahead of the site gaining the ability to index (and, presumably, link to) off-site, 3rd-party content.

The only alternative that comes to mind is pretty janky: 

- do a 1 time copy of the cue-by-example k8s tutorial's markdown into, say, `/docs/content/tutorial/kubernetes` (a proper *import* isn't required, as it'll never be displayed), so that it shows up in the search index
- place a Netlify redirect from `/docs/content/tutorial/kubernetes` over to the canonical cue-by-example URL

*Q*: static link and words on https://alpha.cuelang.org/docs/tutorial/about-these-tutorials/, special-casing the k8s tutorial on that page? Or my janky redirector idea? @myitcv

**Comment by jpluscplusm** [comment]
@myitcv ping on the questions in https://github.com/cue-lang/docs-and-content/issues/21#issuecomment-1788869705.

**Comment by jpluscplusm** [comment]
We'll create a cuelang.org tutorial page that points to the real cue-by-example page. It will contain info that points the reader offsite with an explanation, alongside appropriate keywords so that onsite search can find the page when the user doesn't already know that it exists.

**Comment by jpluscplusm** [comment]
https://cuelang.org/cl/1176897

**Comment by jpluscplusm** [comment]
Closed via https://github.com/cue-lang/cuelang.org/commit/9de17be7a8d65abf3ee90e9172459759b2ccf693
