### ISSUE TITLE
concept guide: existing content from /docs/about/

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/docs-and-content#22]
https://cuelang.org/docs/about/ doesn't have a direct equivalent on alpha, but https://alpha.cuelang.org/docs/introduction/what-is-cue/ (an empty placeholder) seems like a good candidate page.

**Q: shall we copy the page across?**

**Comment by myitcv** [comment]
> Q: shall we copy the page across?

For now, yes.

**Comment by jpluscplusm** [comment]
After having spent the time to import it to /docs/introduction (see https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1171270/2), I discovered I'd somehow missed the previous import of the content we did to https://alpha.cuelang.org/docs/introduction/welcome/.

Genuinely not sure how I missed that 🤦

**Comment by jpluscplusm** [comment]
Closed via https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1171270
