### ISSUE TITLE
No mention of docker image for CUE

### ISSUE THREAD

**Issue by myitcv** [cue-lang/docs-and-content#63]
No pages on https://alpha.cuelang.org mention the [CUE Docker image](https://hub.docker.com/r/cuelang/cue), not even https://alpha.cuelang.org/docs/introduction/installation/. We should fix that.

As part of this change, we should also ensure that https://github.com/cue-lang/cue/blob/master/README.md is in agreement with whatever docs we have on https://alpha.cuelang.org

**Comment by jpluscplusm** [comment]
Mention of Docker was added in https://cuelang.org/cl/1195017.
Synchronisation of the `cue-lang/{cue,cuelang.org}` repos' contents is performed by https://cuelang.org/cl/1197388

**Comment by jpluscplusm** [comment]
I don't know why submitting https://cuelang.org/cl/1197388 didn't close this issue.
