### ISSUE TITLE
howto: log stats from the CUE evaluator

### ISSUE THREAD

**Issue by myitcv** [cue-lang/docs-and-content#9]
Based on various exchanges on slack and elsewhere, having a quick howto would enable us to refer folks to a central place.

**Comment by jpluscplusm** [comment]
https://cuelang.org/cl/1176904

**Comment by jpluscplusm** [comment]
Closed via https://github.com/cue-lang/cuelang.org/commit/b9b20a22b75cd1a5f5a3b33ff2a68ae6a5d6f85d
