### ISSUE TITLE
docs/tutorial: how to use modules with the Go API

### ISSUE THREAD

**Issue by myitcv** [cue-lang/docs-and-content#94]
Now that we have landed https://github.com/cue-lang/cue/releases/tag/v0.8.0-alpha.4 we can land a tutorial (to partner the existing https://alpha.cuelang.org/docs/tutorial/working-with-a-custom-module-registry/) that explains how to use modules via the Go API.

**Comment by jpluscplusm** [comment]
Closed via https://github.com/cue-lang/cuelang.org/commit/1067927641b24c2cb5717ac0979be7a7f50de5a0
